### Send POST 회원 가입 ADMIN
POST http://localhost:8000/api/members/signup
Content-Type: application/json

{
  "userId": "admin",
  "name": "김철수",
  "email": "admin1@example.com",
  "password": "1111",
  "phone": "010-1111-1111",
  "role": "ADMIN"
}


### Send POST 회원 가입 USER
POST http://localhost:8000/api/members/signup
Content-Type: application/json

{
  "userId": "user",
  "name": "홍길동",
  "email": "user@example.com",
  "password": "1111",
  "phone": "010-2222-2222",
  "role": "USER"
}

























































































































































































































































































































































































### Send PUT request with json body
PUT http://localhost:8050/api/admin/orders?orderItemId=1
Content-Type: application/json

{
  "email": "1@aaa.com",
  "address": "서울시",
  "postcode": "11111",
  "productName": "커피 테스트 1",
  "price": "1234",
  "quantity": "3",
  "category": "COFFEE_BEAN_PACKAGE"
}


### GET request with a header
GET http://localhost:8050/api/admin/orders/orderlist?adminPassword=



























































































































































































































































































































































































### Send POST request with json body
POST http://localhost:8000/api/inquiries
Content-Type: application/json

{
  "memberId": "1",
  "inquiryCategory": "MEMBER",
  "inquiryTitle": "문의제목테스트",
  "inquiryContent": "문의내용테스트"
}


### Send POST request with json body
POST http://localhost:8000/api/inquiries/1
Content-Type: application/json

[
  {
    "email": "ccc@ccc.com",
    "address": "sesss",
    "postcode": "123123",
    "productName": "커피 테스트 1",
    "price": 11111,
    "quantity": 5,
    "category": "COFFEE_BEAN_PACKAGE"
  },
  {
    "email": "ccc@ccc.com",
    "address": "sesss",
    "postcode": "123123",
    "productName": "커피 테스트 3",
    "price": 2222,
    "quantity": 1,
    "category": "COFFEE_BEAN_PACKAGE"
  }
]


### Send POST request with json body
DELETE http://localhost:8050/api/orders?email=ccc@ccc.com


### Send POST request with json body
DELETE http://localhost:8050/api/orders/1/1?email=1@aaa.com


### Send PUT request with json body
PUT http://localhost:8050/api/orders/orderItems/3
Content-Type: application/json

{
  "email": "1@aaa.com",
  "address": "서울시",
  "postcode": "11111",
  "productName": "커피 테스트 4",
  "price": "1234",
  "quantity": "3",
  "category": "COFFEE_BEAN_PACKAGE"
}


### Send POST request with json body
DELETE http://localhost:8050/api/admin/2?email=2@aaa.com











### Send POST 문의 등록
POST http://localhost:8000/api/inquiries
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiVVNFUiIsIm5hbWUiOiJuZXdVc2VyTmFtZSIsInVzZXJJZCI6Im5ld1VzZXIiLCJlbWFpbCI6Im5ld1VzZXJAZXhhbXBsZS5jb20iLCJtZW1iZXJJZCI6Mzd9.Y8pW7L1NAs1k0ba5pFgUj7jLOm4H4AkJIJj1hKKZb8E

{
  "inquiryCategory": "MEMBER",
  "inquiryTitle": "newUser 새로운 문의 제목",
  "inquiryContent": "newUser 새로운 문의 내용"
}


### GET 문의 단건 조회
GET http://localhost:8000/api/inquiries/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiVVNFUiIsIm5hbWUiOiJuZXdVc2VyTmFtZSIsInVzZXJJZCI6Im5ld1VzZXIiLCJlbWFpbCI6Im5ld1VzZXJAZXhhbXBsZS5jb20iLCJtZW1iZXJJZCI6Mzd9.Y8pW7L1NAs1k0ba5pFgUj7jLOm4H4AkJIJj1hKKZb8E



### GET 문의 전체 조회
GET http://localhost:8000/api/inquiries
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiVVNFUiIsIm5hbWUiOiJuZXdVc2VyTmFtZSIsInVzZXJJZCI6Im5ld1VzZXIiLCJlbWFpbCI6Im5ld1VzZXJAZXhhbXBsZS5jb20iLCJtZW1iZXJJZCI6Mzd9.Y8pW7L1NAs1k0ba5pFgUj7jLOm4H4AkJIJj1hKKZb8E




### Send PUT 문의 수정
PUT http://localhost:8000/api/inquiries/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiVVNFUiIsIm5hbWUiOiJuZXdVc2VyTmFtZSIsInVzZXJJZCI6Im5ld1VzZXIiLCJlbWFpbCI6Im5ld1VzZXJAZXhhbXBsZS5jb20iLCJtZW1iZXJJZCI6Mzd9.Y8pW7L1NAs1k0ba5pFgUj7jLOm4H4AkJIJj1hKKZb8E

{
  "inquiryCategory": "MEMBER",
  "inquiryTitle": "newUser문의 제목 수정",
  "inquiryContent": "newUser문의 내용 수정"
}


### Send DELETE 문의 삭제
DELETE http://localhost:8000/api/inquiries/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiVVNFUiIsIm5hbWUiOiJuZXdVc2VyTmFtZSIsInVzZXJJZCI6Im5ld1VzZXIiLCJlbWFpbCI6Im5ld1VzZXJAZXhhbXBsZS5jb20iLCJtZW1iZXJJZCI6Mzd9.Y8pW7L1NAs1k0ba5pFgUj7jLOm4H4AkJIJj1hKKZb8E



### Send POST 문의 답변
POST http://localhost:8000/api/inquiries/3/answer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJuYW1lIjoiYWRtaW4iLCJ1c2VySWQiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJtZW1iZXJJZCI6MzZ9.ji2n5POf9DKzdS54cXA5TCQ5sz1q1E8FH2qNOJKEsxY

{
  "replyContent": "newUser 새로운 문의 답변"
}








### Send POST 회원 가입
POST http://localhost:8000/api/members/signup
Content-Type: application/json

{
  "userId": "newUser2",
  "name": "newUserName2",
  "email": "newUser2@example.com",
  "password": "1111",
  "phone": "010-1111-2222",
  "role": "USER"
}


### Send POST 회원 가입 ADMIN
POST http://localhost:8000/api/members/signup
Content-Type: application/json

{
  "userId": "admin",
  "name": "admin",
  "email": "admin@example.com",
  "password": "1111",
  "phone": "010-2222-2222",
  "role": "ADMIN"
}



### 회원 로그인 POST
POST http://localhost:8000/api/members/login
Content-Type: application/json

{
  "userId": "admin",
  "password": "1111"
}



### 회원 로그인 POST
POST http://localhost:8000/api/members/login
Content-Type: application/json

{
  "userId": "user3",
  "password": "1111"
}



### 회원 사진 GET
GET http://localhost:8000/api/members/1/avatar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiVVNFUiIsIm5hbWUiOiLtmY3quLjrj5kiLCJ1c2VySWQiOiJ1c2VyMSIsImVtYWlsIjoidXNlckBnbWFpbC5jb20iLCJtZW1iZXJJZCI6MX0.LRZGygAdQFTYyiDNc6d0mtGHLLbkDsNFb3APmvoevnU



### GET request with a header
GET http://localhost:8000/api/members
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJuYW1lIjoidGVzdE5hbWUiLCJ1c2VySWQiOiJ0ZXN0QWRtaW5JZCIsImVtYWlsIjoidGVzdEFkbWluQGV4YW1wbGUuY29tIn0.EeyT4faUrrJkeTXBtiog8VrZ5lN24v0ehXlgdvoQL88



### GET 관리자 회원 조회
GET http://localhost:8000/api/members/16
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJuYW1lIjoibmV3QWRtaW5OYW1lIiwidXNlcklkIjoibmV3QWRtaW4iLCJlbWFpbCI6Im5ld0FkbWluQGV4YW1wbGUuY29tIiwibWVtYmVySWQiOjE3fQ.EaeTCm5DW2-W6dJyIb2Of1OM7cxNnLQJYxmgMzUOmf8



### GET 관리자 회원 삭제
DELETE http://localhost:8000/api/members/16
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJuYW1lIjoibmV3QWRtaW5OYW1lIiwidXNlcklkIjoibmV3QWRtaW4iLCJlbWFpbCI6Im5ld0FkbWluQGV4YW1wbGUuY29tIiwibWVtYmVySWQiOjE3fQ.EaeTCm5DW2-W6dJyIb2Of1OM7cxNnLQJYxmgMzUOmf8



### Send PUT request with json body
PUT http://localhost:8000/api/members/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiVVNFUiIsIm5hbWUiOiJ0ZXN0TmFtZSIsInVzZXJJZCI6InRlc3RVc2VySWQyIiwiZW1haWwiOiJ0ZXN0VXNlcjJAZXhhbXBsZS5jb20ifQ.eNXhu3RfOTMNQqD0WGHNZuaIGdGS7RJg_v7q4NVZYs0
Content-Type: application/json

{
  "userId": "testUserId2",
  "name": "updatedName",
  "email": "updated@example.com",
  "phone": "010-1111-2222",
  "avatarImage": "updated.png",
  "role": "ADMIN"
}



### GET request with a header
GET http://localhost:8000/api/members/10/avatar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiVVNFUiIsIm5hbWUiOiJ0ZXN0TmFtZSIsInVzZXJJZCI6InRlc3RVc2VySWQzIiwiZW1haWwiOiJ0ZXN0VXNlcjNAZXhhbXBsZS5jb20iLCJtZW1iZXJJZCI6MTB9.BXGIf0dZmtCdopr8a0IdD7Iyu78gK4FMPvKKSmO89g4




### POST 크롤링 상세페이지
POST http://localhost:8000/api/petitions/petitioncrawl/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJuYW1lIjoiYWRtaW4iLCJ1c2VySWQiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJtZW1iZXJJZCI6Mn0.DQuzdP4iwtXBlLgPe45RdtTQwhUsIfWzU74Y646QcDc


### GET 청원 단건 조회
GET http://localhost:8000/api/petitions/1


### GET 청원 전체 조회
GET http://localhost:8000/api/petitions?page=1&size=10



### GET 청원 만료일 순 5개 조회
GET http://localhost:8000/api/petitions/view/endDate



### GET 청원 동의자 순 5개 조회
GET http://localhost:8000/api/petitions/view/agreeCount


### GET 청원 삭제
DELETE http://localhost:8000/api/petitions/57




### POST 청원 좋아요 기능
POST http://localhost:8000/api/petitions/2/like?memberId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiVVNFUiIsIm5hbWUiOiJuZXdVc2VyTmFtZSIsInVzZXJJZCI6Im5ld1VzZXIiLCJlbWFpbCI6Im5ld1VzZXJAZXhhbXBsZS5jb20iLCJtZW1iZXJJZCI6MX0.Ewo83EhQAUmR-Q5gCkl_Zg-UOC5CZBWCHtvcJ2G1v4o








### POST 관리자 로그인
POST http://localhost:8000/api/members/login
Content-Type: application/json

{
  "userId": "admin",
  "password": "1111"
}


### POST 크롤링 상세페이지
POST http://localhost:8000/api/petitions/petitioncrawl/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJuYW1lIjoiYWRtaW4iLCJ1c2VySWQiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJtZW1iZXJJZCI6Mn0.DQuzdP4iwtXBlLgPe45RdtTQwhUsIfWzU74Y646QcDc

